feature: products

routes:
  - /products?limit=10&skip=10
  - /products/add

ui:
  list: datatable
  create: modal + form

api:
  queries:
    - getProducts

  mutations:
    - addProduct

forms:
  ProductForm:
    fields:
      title:
        type: string
        required: true
      price:
        type: decimal
        required: true
      description:
        type: string
        required: false

queryKeys:
  - products.all
  - products.byId

mutationKeys:
  - products.add
  - products.update

apiResponses:
  getProducts:
    success:
      status: 200
        # Body is now referenced from a separate JSON file for easy editing/copying
        body:
          $ref: './responses/getProducts.json'
